export const tabSqls = {
	dataVersion: 4,
	tabName: ['SessionList', 'NormalMessage', 'GroupMessage', 'GroupNotice', 'ImUser','GroupImUser'],
	fileTabName:['FileList'],
	editContent:[],
	SessionList: 'SessionList',
	NormalMessage: 'NormalMessage',
	GroupMessage: 'GroupMessage',
	GroupNotice: 'GroupNotice',
	ImUser: 'ImUser',
	GroupImUser:'GroupImUser',
	FileList:'FileList',
	createImUserSql: `CREATE TABLE IF NOT EXISTS ImUser(
	 ImId INTEGER NOT NULL PRIMARY KEY,
	 UserId INTEGER,
	 AppId INTEGER,
	 AppUserId TEXT,
	 Name TEXT,
	 Gender INT,
	 TelPhone TEXT,
	 Email TEXT,
	 AvatarFileId TEXT,
	 CustomField TEXT,
	 Initial TEXT,
	 Type INT
	);`,
	createGroupImUserSql: `CREATE TABLE IF NOT EXISTS GroupImUser(
	 GroupIdAndImId TEXT NOT NULL PRIMARY KEY,
	 ImId INTEGER NOT NULL,
	 GroupId INTEGER NOT NULL,
	 UserId INTEGER,
	 AppId INTEGER,
	 AppUserId TEXT,
	 Name TEXT,
	 Gender INT,
	 TelPhone TEXT,
	 Email TEXT,
	 AvatarFileId TEXT,
	 CustomField TEXT,
	 Initial TEXT,
	 Type INT
	);`,
	createSessionListSql: `CREATE TABLE IF NOT EXISTS SessionList(
		TargetId INTEGER NOT NULL PRIMARY KEY,
		UserId INTEGER NOT NULL,
		SessionId INTEGER,
		UnreadCount INTEGER,
		LastContent TEXT,
		LastTime INTEGER,
		ChangeTime INTEGER,
		Type INTEGER,
		IsTopMost INTEGER,
		TargetName TEXT,
		TargetAvatarFileId INTEGER,
		LastUserId INTEGER,
		CustomField TEXT
	);`,
	createNormalMessageSql: `CREATE TABLE IF NOT EXISTS NormalMessage(
		KeyID TEXT NOT NULL PRIMARY KEY,
		Id INTEGER,
		TargetId INTEGER,
		ReferenceId INTEGER,
		SourceId INTEGER NOT NULL,
		CreateTime INTEGER NOT NULL,
		ChangeTime INTEGER,
		Type INTEGER,
		MessageType INTEGER,
		Content TEXT,
		FileId INTEGER,
		SourceName TEXT,
		CustomContent TEXT,
		SourceAvatarId INTEGER,
		CustomType TEXT,
		Status INT
	);`,
	createGroupMessageSql: `CREATE TABLE IF NOT EXISTS GroupMessage(
	    KeyID TEXT NOT NULL PRIMARY KEY,
	    Id INTEGER,
		GroupId INTEGER NOT NULL,
		AtUsers INTEGER,
		CustomContent TEXT,
		SharpUsers INTEGER,
		ReferenceId INTEGER,
		SourceId INTEGER NOT NULL,
		CreateTime INTEGER,
		ChangeTime INTEGER,
		MessageType INTEGER,
		Type INT,
		Content TEXT,
		FileId INTEGER,
		SourceName TEXT,
		SourceAvatarId INTEGER,
		CustomType TEXT,
		Status INT
	);`,
	createGroupNoticeSql: `CREATE TABLE IF NOT EXISTS GroupNotice(
		Key INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
		Id INTEGER,
		GroupId INTEGER NOT NULL,
		IsConfirm TEXT,
		ReferenceId TEXT,
		SourceId INTEGER,
		CustomContent TEXT,
		CreateTime INTEGER,
		Type INT,
		Content TEXT,
		FileId INTEGER
	);`,
	createFileListSql: `CREATE TABLE IF NOT EXISTS FileList(
		Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	    Date INTEGER,
		LocalPath TEXT,
		NetPath TEXT
	);`
}
